[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = [
  'rm -rf backend/src/scripts',
  'cd backend && npm install'
]

[phases.build]
cmds = [
  'rm -rf backend/src/scripts',
  'cd backend && npm run build'
]

[start]
cmd = 'cd backend && node dist/index.js'
